version: "3"
services:
  backend:
    image: prebid-server
    environment:
      - GDPR_DEFAULT_VALUE=0
      - PBS_CACHE_SCHEME=https
      - PBS_CACHE_HOST=prebid.adnxs.com/pbc/v1
      - PBS_EXTERNAL_CACHE_SCHEME=https
      - PBS_EXTERNAL_CACHE_HOST=prebid.adnxs.com
      - PBS_EXTERNAL_CACHE_PATH=/pbc/v1/cache
      - PBS_ACCOUNT_REQUIRED=0
      - PBS_ACCOUNT_DEBUG_ALLOW=1
      - PBS_STORED_REQUESTS_DATABASE_CONNECTION_DRIVER=mysql
      - PBS_STORED_REQUESTS_DATABASE_CONNECTION_DBNAME=anvil_prod
      - PBS_STORED_REQUESTS_DATABASE_CONNECTION_HOST=db
      - PBS_STORED_REQUESTS_DATABASE_CONNECTION_PORT=3306
      - PBS_STORED_REQUESTS_DATABASE_CONNECTION_USER=prebid-server
      - PBS_STORED_REQUESTS_DATABASE_CONNECTION_PASSWORD=test123
      - PBS_STORED_REQUESTS_DATABASE_FETCHER_QUERY=SELECT id, payload as data, requestType as type FROM stored_requests where id in $$REQUEST_ID_LIST or id in $$IMP_ID_LIST;
      - PBS_STORED_REQUESTS_DATABASE_FETCHER_AMP_QUERY=SELECT id, payload, 'request' FROM stored_request where requestType = 'amp' and id in $$REQUEST_ID_LIST;
    ports:
      - 8000:8000
    networks:
      - public
      - private
    depends_on:
      - db
  db:
    image: mysql:8.0.27
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ~/db-data:/var/lib/mysql
    networks:
      - private
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=anvil_prod
      - MYSQL_USER=prebid-server
      - MYSQL_PASSWORD=test123
networks:
  public:
  private:
